apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: <Test-new-api-mat-format>
  description: Testing new api mat marker format
  va:
    maturity-markers: # This is the section that contains the maturity markers
      version: 1
      documentation:
      - legacyFormat
      - vaNetwork
      architecture:
      - rest
      lowerEnvironmentAccess:
      - lessThan2
      productionAccess:
      - moreThan2
      performance:
      - p95Less
      reliability:
      - sloExists
      - slo99
      - follow
      apiStatus:
      - logs
      - metrics
      support:
      - activelyMaintained
      hosting:
      - cloudAuto
      testData:
      - testAvailable
      - testAvailableDocumentation
  intendedConsumer: Internal VA Developers
  annotations:
    backstage.io/techdocs-ref: url:<link-to-git-repo>
    github.com/project-slug: department-of-veterans-affairs/<repo-name>
  tags:
    - code-va-test-set
  links:
    - url: <link-to-api-documentation>
      title: Public Docs
      icon: web
spec:
  type: openapi
  lifecycle: production
  owner: <team-name>
  system: Lighthouse
  definition:
    $text: <link-to-swagger-json>
